### ISSUE TITLE
Cannot 

### ISSUE THREAD

**Issue by markhughes321** [bab2683/babdev#20]
Braulio,

When I try to run the app I'm getting the following error

Command:
`npm run generate-apps-tsconfig && ng serve main-angular --open=true --port 4400",

Error:
ERROR in Cannot read property 'loadChildren' of undefined

**Comment by bab2683** [comment]
Did you run npm install first?

**Comment by bab2683** [comment]
Also, to run the main angular app just do `npm run start:main`
